version: '3.9'

services:

  jms:
    container_name: jms
    image: vromero/activemq-artemis
    environment:
      ARTEMIS_USERNAME: 'leonardodagios'
      ARTEMIS_PASSWORD: 'live'
    ports:
      - "61616:61616"
      - "8161:8161"
    expose:
      - "61616"
      - "8161"

  produto:
    container_name: produto
    image: leonardodagios/produto:1.0
    ports:
      - "8080:8080"
    expose:
      - "8080"
    depends_on:
      - jms
